### ISSUE TITLE
Regarding the Asset Library submission

### ISSUE THREAD

**Issue by vnen** [AlansCodeLog/godot-gimbal-control-node#1]
I got here while moderating you [submission to Godot's Asset Library](https://godotengine.org/asset-library/asset/edit/615). The issue is that this repository contains a whole project and not only a plugin.

If the intention is to have this as a template, change the category in the submission to Template (you can edit it). Otherwise remove everything from the repository that is project related. You may leave a demo scene if you want, but without project files, especially without the `.import` folder. You also may create a new repository for your demo.

You can ping me here after you made the changes (or before if you have any doubts). Thanks!

**Comment by alanscodelog** [comment]
Oh, I didn't know, there wasn't much documentation about how the submission should be structured, what it should include/exclude.

Should I also remove any files ending in `.import` as well? I'm assuming these aren't needed so long as none of the import parameters were changed, right?

I think I might end up separating the demos in a new repo. I'll @ you when it's done.

**Comment by vnen** [comment]
Yeah, we really need to document the submission process.

You don't need to delete the `*.import` files, it's okay to have the import options stored even if it's the default.

**Comment by alanscodelog** [comment]
Okay I have separated the plugin from the demos and modified the info on the asset submission.

Regarding the documentation I see there aren't any issues open about this on godot-docs, at least not that I can find. Do you know if anyone is working on this? Should I open an issue? I'd like to help if I can.

**Comment by vnen** [comment]
I remember a few discussion, but not sure if it was on GitHub or not. If you can't find an issue about it, feel free to open one. I don't think there's anyone working on this right now, but it's good to remind.

I approved the in the Asset Library so it should be available now: https://godotengine.org/asset-library/asset/194. Thanks!
